language: python
git:
  # We need a deeper depth for 'git descibe' to ensure
  # we can reach the last tagged version.
  depth: 99999

python:
  - "2.7"
  - "3.5"

# Use the new travis docker based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

# Install required packages
addons:
  postgresql: "9.4"
  apt:
    packages:
    - libhdf5-serial-dev
    - libnetcdf-dev
    - libproj-dev
    - libgdal1-dev
    - libudunits2-dev
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  # Create a database for the integration tests.
  # - createdb agdcintegration

install:
  - export CPLUS_INCLUDE_PATH="/usr/include/gdal"
  - export C_INCLUDE_PATH="/usr/include/gdal"
  - travis_retry pip install --upgrade pip
  - travis_retry pip install pylint==1.5 coveralls gdal==1.10.0 compliance-checker
  - pip install git+git://github.com/data-cube/agdc-v2.git@stable
  - travis_retry pip install .

script:
  - ./check-code.sh

after_success:
  - coveralls

